import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProps } from "next/app";
import DocsLayout from "@/components/layout/docs-layout";
import { ThemeProvider } from "react-material";

const roboto = localFont({
  src: "./fonts/RobotoVF.ttf",
  variable: "--font-roboto",
});
const dmsans = localFont({
  src: "./fonts/DMSansVF.ttf",
  variable: "--font-dmsans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Root({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider>
      <main className={`${roboto.variable} ${dmsans.variable}`}>
        <DocsLayout>
          <Component {...pageProps} />
        </DocsLayout>
      </main>
    </ThemeProvider>
  );
}
